{{- if .Values.azure.enabled }}
apiVersion: infrastructure.opendatahub.io/v1alpha1
kind: AzureKubernetesEngine
metadata:
  name: default-azurekubernetesengine
  labels:
    {{- include "rhaii-helm-chart.labels" . | nindent 4 }}
spec:
  dependencies:
    certManager:
      configuration: {}
      managementPolicy: {{ .Values.azure.kubernetesEngine.dependencies.certManager.managementPolicy }}
    gatewayAPI:
      configuration: {}
      managementPolicy: {{ .Values.azure.kubernetesEngine.dependencies.gatewayAPI.managementPolicy }}
    lws:
      configuration: {}
      managementPolicy: {{ .Values.azure.kubernetesEngine.dependencies.lws.managementPolicy }}
    sailOperator:
      configuration: {}
      managementPolicy: {{ .Values.azure.kubernetesEngine.dependencies.sailOperator.managementPolicy }}
{{- end }}
