apiVersion: v1
kind: Service
metadata:
  name: opendatahub-operator-controller-manager-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app.kubernetes.io/name: opendatahub-operator-controller-manager-service
