apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authorino-operator-manager-role
rules:
  # Core API resources
  - apiGroups:
      - ""
    resources:
      - events
      - configmaps
      - secrets
      - services
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  # Apps
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - get
      - patch
      - update
  # Coordination
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # AuthConfigs
  - apiGroups:
      - authorino.kuadrant.io
    resources:
      - authconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - authorino.kuadrant.io
    resources:
      - authconfigs/status
    verbs:
      - get
      - patch
      - update
  # Authorinos
  - apiGroups:
      - operator.authorino.kuadrant.io
    resources:
      - authorinos
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.authorino.kuadrant.io
    resources:
      - authorinos/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - operator.authorino.kuadrant.io
    resources:
      - authorinos/finalizers
    verbs:
      - update
  # RBAC
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Auth
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authorino-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authorino-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: authorino-operator
    namespace: {{ .Values.operatorNamespace }}
