apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-operator-manager-role
rules:
  # Core API resources
  - apiGroups:
      - ""
    resources:
      - events
      - configmaps
      - secrets
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
  # Coordination
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # DNS CRDs
  - apiGroups:
      - kuadrant.io
    resources:
      - dnsrecords
      - dnshealthcheckprobes
      - dnspolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kuadrant.io
    resources:
      - dnsrecords/status
      - dnshealthcheckprobes/status
      - dnspolicies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - kuadrant.io
    resources:
      - dnsrecords/finalizers
      - dnshealthcheckprobes/finalizers
      - dnspolicies/finalizers
    verbs:
      - update
  # Gateway API
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
      - httproutes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways/status
    verbs:
      - get
  # Auth
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: dns-operator-controller-manager
    namespace: {{ .Values.operatorNamespace }}
