apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-operator-controller-manager
  namespace: {{ .Values.operatorNamespace }}
  labels:
    app.kubernetes.io/component: dns-operator
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/component: dns-operator
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/component: dns-operator
    spec:
      serviceAccountName: dns-operator-controller-manager
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: {{ .Values.images.operators.dns }}
          imagePullPolicy: IfNotPresent
          args:
            - --metrics-bind-address=:8080
            - --leader-elect
          env:
            - name: WATCH_NAMESPACES
              value: ""
            - name: CLUSTER_SECRET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sku
                operator: NotIn
                values: ["gpu"]
