apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kuadrant-operator-pdb
  namespace: {{ .Values.operatorNamespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/component: kuadrant-operator
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authorino-operator-pdb
  namespace: {{ .Values.operatorNamespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/component: authorino-operator
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: limitador-operator-pdb
  namespace: {{ .Values.operatorNamespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/component: limitador-operator
