apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuadrant-operator-controller-manager
  namespace: {{ .Values.operatorNamespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authorino-operator
  namespace: {{ .Values.operatorNamespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: limitador-operator-controller-manager
  namespace: {{ .Values.operatorNamespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-operator-controller-manager
  namespace: {{ .Values.operatorNamespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
