{{- $xksGatewayEnabled := index .Values "xks-gateway" "enabled" }}
{{- if and .Values.enabled $xksGatewayEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rhai-gateway-crd-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rhai-on-xks-chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-delete
    helm.sh/hook-weight: "-12"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerConfigJson | default "{}" | b64enc }}
{{- end }}
