{{- $dep := .Values.dependencies.rhcl -}}
{{- $shouldInstall := include "rhoai-dependencies.shouldInstall" (dict "dependencyName" "rhcl" "dependency" $dep "dependencies" .Values.dependencies "components" .Values.components "services" .Values.services) -}}
{{- if eq $shouldInstall "true" }}
{{- $gwClass := $dep.config.gatewayClass | default dict -}}
{{- $create := $gwClass.create | default "auto" | toString -}}
{{- if or (eq $create "true") (eq $create "auto") }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ $gwClass.name }}
  labels:
    {{- include "rhoai-dependencies.labels" . | nindent 4 }}
spec:
  {{- toYaml $gwClass.spec | nindent 2 }}
{{- end }}
{{- end }}