{{- if and (include "xks-gateway.configured" .) (eq (include "xks-gateway.oidcSecretManaged" .) "true") }}
{{- $gw := .Values.gateway -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xks-gateway.oidcClientSecretRefName" . }}
  namespace: {{ include "xks-gateway.oidcSecretNamespace" . }}
  labels:
    {{- include "xks-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ $gw.oidc.clientSecretRef.key | default "client-secret" }}: {{ $gw.oidc.oidcClientSecret | quote }}
{{- end }}
