---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cluster-validation
spec:
  params:
    - name: git-url
      type: string
    - name: revision
      type: string
    - name: ocp-version
      type: string
    - name: instance-type
      type: string
      default: "m5.xlarge"
    - name: validation-type
      type: string
      default: "kustomize"
      description: "Type of validation to run: kustomize or helm"
    - name: olm-catalog-image
      type: string
      default: ""
      description: "Optional OLM catalog image to install (e.g. quay.io/rhoai/rhoai-fbc-fragment:rhoai-3.2)"
    - name: olm-channel
      type: string
      default: ""
      description: "Optional OLM channel to use for operator subscription (e.g. fast, stable)"
  tasks:
    - name: provision-eaas-space
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)

    - name: provision-and-validate
      runAfter:
        - provision-eaas-space
      taskSpec:
        params:
          - name: git-url
            type: string
          - name: git-revision
            type: string
          - name: ocp-version
            type: string
          - name: instance-type
            type: string
          - name: eaas-space-secret-ref
            type: string
          - name: validation-type
            type: string
          - name: olm-catalog-image
            type: string
          - name: olm-channel
            type: string
        results:
          - name: clusterName
            description: Name of the provisioned cluster
          - name: status
            description: Overall validation status
        volumes:
          - name: credentials
            emptyDir: {}
          - name: workspace
            emptyDir: {}
        steps:
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(params.eaas-space-secret-ref)
              - name: version
                value: $(params.ocp-version)
              - name: instanceType
                value: $(params.instance-type)

          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(params.eaas-space-secret-ref)
              - name: clusterName
                value: $(steps.create-cluster.results.clusterName)
              - name: credentials
                value: credentials

          - name: verify-cluster-and-clone
            image: quay.io/konflux-ci/appstudio-utils:latest
            workingDir: /workspace
            env:
              - name: KUBECONFIG
                value: /credentials/$(steps.get-kubeconfig.results.kubeconfig)
              - name: OCP_VERSION
                value: $(params.ocp-version)
            volumeMounts:
              - name: credentials
                mountPath: /credentials
              - name: workspace
                mountPath: /workspace
            script: |
              #!/bin/bash
              set -e

              echo "=== Verifying cluster access (OCP ${OCP_VERSION}) ==="
              oc version
              oc get nodes
              echo "✅ Cluster is accessible"

              echo ""
              echo "=== Cloning repository ==="
              git clone $(params.git-url) repo
              cd repo
              git checkout $(params.git-revision)
              echo "✅ Repository cloned"

          - name: run-validation
            image: quay.io/konflux-ci/appstudio-utils:latest
            workingDir: /workspace/repo
            env:
              - name: KUBECONFIG
                value: /credentials/$(steps.get-kubeconfig.results.kubeconfig)
              - name: OCP_VERSION
                value: $(params.ocp-version)
              - name: CLUSTER_NAME
                value: $(steps.create-cluster.results.clusterName)
              - name: VALIDATION_TYPE
                value: $(params.validation-type)
              - name: OLM_CATALOG_IMAGE
                value: $(params.olm-catalog-image)
              - name: OLM_CHANNEL
                value: $(params.olm-channel)
            volumeMounts:
              - name: credentials
                mountPath: /credentials
              - name: workspace
                mountPath: /workspace
            script: |
              #!/bin/bash
              set -e

              echo "=== Running ${VALIDATION_TYPE} validation on OCP ${OCP_VERSION} ==="

              # Install custom OLM catalog if specified
              if [ -n "${OLM_CATALOG_IMAGE}" ]; then
                echo ""
                echo "=== Installing custom OLM catalog ==="
                echo "Catalog image: ${OLM_CATALOG_IMAGE}"

                cat <<EOF | oc apply -f -
              apiVersion: operators.coreos.com/v1alpha1
              kind: CatalogSource
              metadata:
                name: custom-catalog
                namespace: openshift-marketplace
              spec:
                sourceType: grpc
                image: ${OLM_CATALOG_IMAGE}
                displayName: Custom Catalog
                publisher: Custom
                updateStrategy:
                  registryPoll:
                    interval: 30m
              EOF

                echo "Waiting for catalog source to be ready..."
                # Wait for the catalog pod to be created and running
                for i in {1..30}; do
                  POD_STATUS=$(oc get pods -n openshift-marketplace -l olm.catalogSource=custom-catalog -o jsonpath='{.items[0].status.phase}' 2>/dev/null || echo "NotFound")
                  if [ "${POD_STATUS}" = "Running" ]; then
                    echo "Catalog pod is running"
                    break
                  fi
                  echo "Waiting for catalog pod... (attempt ${i}/30, status: ${POD_STATUS})"
                  if [ "${POD_STATUS}" = "ImagePullBackOff" ] || [ "${POD_STATUS}" = "ErrImagePull" ]; then
                    echo "ERROR: Failed to pull catalog image. Check if the image exists and credentials are configured."
                    oc get pods -n openshift-marketplace -l olm.catalogSource=custom-catalog -o yaml
                    exit 1
                  fi
                  sleep 10
                done

                echo "✅ Custom OLM catalog installed"
              fi

              # Build additional helm args if custom catalog or channel is specified
              HELM_EXTRA_ARGS=""
              if [ -n "${OLM_CATALOG_IMAGE}" ]; then
                HELM_EXTRA_ARGS="--set operator.odh.olm.source=custom-catalog"
                echo "Using custom catalog for operators: custom-catalog"
              fi
              if [ -n "${OLM_CHANNEL}" ]; then
                HELM_EXTRA_ARGS="${HELM_EXTRA_ARGS} --set operator.odh.olm.channel=${OLM_CHANNEL}"
                echo "Using OLM channel: ${OLM_CHANNEL}"
              fi

              if [ "${VALIDATION_TYPE}" = "helm" ]; then
                # Install helm if not available
                if ! command -v helm &> /dev/null; then
                  echo "Installing Helm..."
                  curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash
                fi

                # Install the chart (first run - operators only)
                echo ""
                echo "=== Install and verify Helm chart ==="
                make helm-install-verify HELM_EXTRA_ARGS="${HELM_EXTRA_ARGS}"

              else
                # Kustomize validation (default)
                echo "=== Applying and verifying dependencies ==="
                make apply-and-verify-dependencies K8S_CLI=oc
              fi

              echo ""
              echo "✅ ${VALIDATION_TYPE} validation completed successfully on OCP ${OCP_VERSION}!"

              # Set results
              echo -n "${CLUSTER_NAME}" | tee $(results.clusterName.path)
              echo -n "success" | tee $(results.status.path)
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.revision)
        - name: ocp-version
          value: $(params.ocp-version)
        - name: instance-type
          value: $(params.instance-type)
        - name: eaas-space-secret-ref
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: validation-type
          value: $(params.validation-type)
        - name: olm-catalog-image
          value: $(params.olm-catalog-image)
        - name: olm-channel
          value: $(params.olm-channel)
