apiVersion: v2
name: rhai-on-openshift-chart
description: A Helm chart for installing ODH/RHOAI dependencies and component configurations
type: application
version: 3.4.0
appVersion: "3.4.0"
keywords:
  - openshift
  - rhoai
  - odh
  - ai
  - rhaii
  - rhai
dependencies:
  - name: grid-enrollment
    version: "0.1.0"
    condition: grid-enrollment.enabled
  - name: grid-operator
    version: "0.1.4"
    condition: grid-operator.enabled
  - name: praxis-gateway
    version: "0.1.4"
    condition: praxis-gateway.enabled
