{{- if .Values.enabled }}
apiVersion: components.platform.opendatahub.io/v1alpha1
kind: Kserve
metadata:
  name: default-kserve
  labels:
    {{- include "rhaii-helm-chart.labels" . | nindent 4 }}
spec:
  {{- with .Values.components.kserve.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
