---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: helm-ocp419-pr{{ pull_request_number }}
  labels:
    appstudio.openshift.io/application: odh-gitops
    appstudio.openshift.io/component: helm-chart-validation-ocp-419
    pipelines.appstudio.openshift.io/type: test
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      files.all.exists(file, file.startsWith('chart/'))
    pipelinesascode.tekton.dev/on-comment: "^/validate-helm-chart"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "{{source_url}}"
      - name: revision
        value: "{{revision}}"
      - name: pathInRepo
        value: .tekton/pipelines/cluster-validation-pipeline.yaml
  params:
    - name: git-url
      value: "{{source_url}}"
    - name: revision
      value: "{{revision}}"
    - name: ocp-version
      value: "4.19.0"
    - name: validation-type
      value: "helm"
    - name: olm-catalog-image
      value: "quay.io/opendatahub/opendatahub-operator-catalog:latest"
    - name: olm-channel
      value: "fast"
    - name: operator-type
      value: "odh"
  taskRunTemplate:
    serviceAccountName: build-pipeline-helm-chart-validation-ocp-419
